name: media_system
networks:
  macvlan_name:
    external: true

services:
  homarr:
    image: ghcr.io/ajnart/homarr
    container_name: homarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${HOMARR_PASSWORD}
    volumes:
      - ${CONFIG_PATH}/homarr/configs:/app/data/configs
      - ${CONFIG_PATH}/homarr/icons:/app/public/icons
    ports:
      - 47575:7575

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 40213:8191

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 40214:9696

  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${CONFIG_PATH}/jproxy/database:/app/database
    ports:
      - 40215:8117

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- JELLYFIN_TYPE=emby
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    ports:
      - 40216:5055
    depends_on:
      - sonarr
      - radarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 40217:7878
    depends_on:
      - jproxy
      - qbittorrent

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 40218:8989
    depends_on:
      - jproxy
      - qbittorrent

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=40219
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_PATH}:/media
    networks:
      default:
      macvlan_name:
          ipv4_address: ${qbittorrent_ip}

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=atm
      - PASS=atm@20230101
      - RPCPORT=40220
      - TRANSMISSION_WEB_HOME=/config/webui/
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${MEDIA_PATH}:/media
      - ${MEDIA_PATH}/watch:/watch
    networks:
      default:
      macvlan_name:
        ipv4_address: ${transmission_ip}

  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyfin/config:/config
      - ${CONFIG_PATH}/jellyfin/cache:/cache
      - ${MEDIA_PATH}:/media #视频目录
      - ${CERT_PATH}:/cert #证书目录
    ports:
      - 48096:8096
      - 7359:7359/udp
      - 1900:1900/udp
