name: media_system

services:
  homarr:
    image: ghcr.io/ajnart/homarr
    container_name: homarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${HOMARR_PASSWORD}
    volumes:
      - ${CONFIG_PATH}/homarr/configs:/app/data/configs
      - ${CONFIG_PATH}/homarr/icons:/app/public/icons
    ports:
      - 47575:7575

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 40213:8191

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 40214:9696

  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${CONFIG_PATH}/jproxy/database:/app/database
    ports:
      - 40215:8117

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- JELLYFIN_TYPE=emby
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    ports:
      - 40216:5055
    depends_on:
      - sonarr
      - radarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 40217:7878
    depends_on:
      - jproxy
      - qbittorrent

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 40218:8989
    depends_on:
      - jproxy
      - qbittorrent

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=40219
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 40219:40219
      - 6881:6881
      - 6881:6881/udp

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    container_name: chinesesubfinder
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/chinesesubfinder:/config
      - ${MEDIA_PATH}:/media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PERMS=true
      - UMASK=022
    hostname: chinesesubfinder
    ports:
      - 40220:19035
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyfin/config:/config
      - ${CONFIG_PATH}/jellyfin/cache:/cache
      - ${MEDIA_PATH}:/media #视频目录
      - ${CERT_PATH}:/cert #证书目录
    ports:
      - 48096:8096
      - 7359:7359/udp
      - 1900:1900/udp
